### ISSUE TITLE
Electrum issues

### ISSUE THREAD

**Issue by qasimsaleem1** [BTCGPU/electrum#50]
<h2>Traceback</h2>
<pre>
Traceback (most recent call last):
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum_gui\qt\network_dialog.py", line 446, in set_server
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\network.py", line 471, in set_parameters
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\network.py", line 486, in switch_lagging_interface
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\blockchain.py", line 422, in read_header
Exception: Expected to read a full header. This was only 0 bytes

</pre>

<h2>Additional information</h2>
<ul>
  <li>ElectrumG version: 3.2.1</li>
  <li>Operating system: Windows-10-10.0.10586</li>
  <li>Wallet type: standard</li>
  <li>Locale: en_US</li>
  <li>Testnet: False</li>
  <li>Regtest: False</li>
</ul>

**Comment by barhat555** [comment]
HELLO!
PLEASE PROMPT WHY WOMAN'S WALLET DOESN'T CONNECT?
VERY LONG ON RED ROUND ICON DOWN ....
ElectrumG version: 3.2.1

**Comment by barhat555** [comment]
HELLO!
PLEASE PROMPT WHY WHY DO I have lectrumG WALLETS WITHOUT CONNECTIONS IN ME?
VERY LONG ON RED ROUND ICON DOWN ....

**Comment by qasimsaleem1** [comment]
Go to tools network then server then tick select server automatically.
Make sure you have working and stable internet connection.

**Comment by qasimsaleem1** [comment]
I use electrum portable you can download it. 
Check this also https://bitcoingold.org/electrumg-guide/

**Comment by qasimsaleem1** [comment]
https://github.com/BTCGPU/electrum/releases
Download electrum portable.

**Comment by barhat555** [comment]
THANKS FOR THE ANSWER!
I DOWNLOADED ON A NEW AND RE-INSTALLED, BUT EVERYTHING IS EQUALLY .... THE WALLET DOES NOT CONNECT!
CONSTANTLY ON RED BUTTON.
ALTHOUGH THE SERVER IS MARKED!

MAY NEED WAIT WAIT FOR IT TO CONNECT ???

**Comment by Lexus247** [comment]
Версия 3.2.1. Не подключается к серверу. Что делать?

**Comment by tt2105** [comment]
"Not connected" v.3.2.1. THE WALLET DOES NOT CONNECT!
CONSTANTLY ON RED BUTTON. 
How to be?
![vv](https://user-images.githubusercontent.com/61073276/87299525-01590480-c52e-11ea-9b3a-e7cc1296a127.png)

**Comment by tt2105** [comment]
Hello
When the wallet starts, the status is no connection and a red button.
Wallet version 3.2.1
Windows 10 Pro
19042.1288
