### ISSUE TITLE
start error then blockchain update halt(?)

### ISSUE THREAD

**Issue by dchmelik** [BTCGPU/electrum#53]
Installed electrumg but see error message below.  Then blockchain synchronization stops long time at 551123/633393; hasn't updated some hours.  I'm on Slackware64 14+-current. w/python3-3.7.2-x86_64-1_SBo.
```
Traceback (most recent call last):
  File "/usr/bin/electrumg", line 425, in <module>
    result = server.gui(config_options)
  File "/usr/lib64/python3.7/site-packages/jsonrpclib/jsonrpc.py", line 748, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.7/site-packages/jsonrpclib/jsonrpc.py", line 630, in _request
    check_for_errors(response)
  File "/usr/lib64/python3.7/site-packages/jsonrpclib/jsonrpc.py", line 1321, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/usr/lib64/python3.7/site-packages/electrum/util.py", line 255, in print_stderr | OSError: [Errno 5] Input/output error\n')
```

**Comment by dchmelik** [comment]
We got similar error on Kubuntu (64-bit) 20.04 w/python3/focal,now 3.8.2-0ubuntu2 amd64... blockchain synchronization stopped a little after in the last case, (537011/634251) but might've restarted.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/electrum_gui/qt/main_window.py", line 634, in timer_actions
    self.update_wallet()
  File "/usr/local/lib/python3.8/dist-packages/electrum_gui/qt/main_window.py", line 758, in update_wallet
    self.update_tabs()
  File "/usr/local/lib/python3.8/dist-packages/electrum_gui/qt/main_window.py", line 761, in update_tabs
    self.history_list.update()
  File "/usr/local/lib/python3.8/dist-packages/electrum_gui/qt/util.py", line 505, in update
    self.on_update()
  File "/usr/local/lib/python3.8/dist-packages/electrum/util.py", line 293, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "/usr/local/lib/python3.8/dist-packages/electrum/util.py", line 289, in do_profile
    o = func(*args, **kw_args)
  File "/usr/local/lib/python3.8/dist-packages/electrum_gui/qt/history_list.py", line 239, in on_update
    status, status_str = self.wallet.get_tx_status(tx_hash, height, conf, timestamp)
  File "/usr/local/lib/python3.8/dist-packages/electrum/wallet.py", line 1171, in get_tx_status
    size = tx.estimated_size()
  File "/usr/local/lib/python3.8/dist-packages/electrum/util.py", line 293, in <lambda>
    return lambda *args, **kw_args: do_profile(func, args, kw_args)
  File "/usr/local/lib/python3.8/dist-packages/electrum/util.py", line 291, in do_profile
    print_error("[profiler]", n, "%.4f"%t)
  File "/usr/local/lib/python3.8/dist-packages/electrum/util.py", line 251, in print_error
    print_stderr(*args)
  File "/usr/local/lib/python3.8/dist-packages/electrum/util.py", line 255, in print_stderr
    sys.stderr.write(" ".join(args) + "\n")
OSError: [Errno 5] Input/output error

```

**Comment by AlfiGitHub** [comment]
I received a message of ElectrumG wallet version 3.2.1 asking me to report this bug. The message is the following:

Traceback
Traceback (most recent call last):
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\util.py", line 770, in run_with_except_hook
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\network.py", line 1035, in run
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\network.py", line 969, in wait_on_sockets
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\network.py", line 593, in process_responses
AssertionError
 
Additional information
ElectrumG version: 3.2.1 
Operating system: Windows-7-6.1.7601-SP1 
Wallet type: standard 
Locale: es_VE 
Testnet: False 
Regtest: False
