### ISSUE TITLE
Synchronizing issue!

### ISSUE THREAD

**Issue by karim-kgawad89** [BTCGPU/electrum#55]
<h2>Traceback</h2>
<pre>
Traceback (most recent call last):
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum_gui\qt\main_window.py", line 76, in onPress
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum_gui\qt\main_window.py", line 1951, in <lambda>
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum_gui\qt\__init__.py", line 176, in show_network_dialog
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum_gui\qt\network_dialog.py", line 48, in __init__
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum_gui\qt\network_dialog.py", line 319, in __init__
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum_gui\qt\network_dialog.py", line 360, in update
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\blockchain.py", line 178, in get_name
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\blockchain.py", line 447, in get_hash
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\blockchain.py", line 422, in read_header
Exception: Expected to read a full header. This was only 0 bytes

</pre>

<h2>Additional information</h2>
<ul>
  <li>ElectrumG version: 3.2.1</li>
  <li>Operating system: Windows-10-10.0.18362-SP0</li>
  <li>Wallet type: standard</li>
  <li>Locale: en_US</li>
  <li>Testnet: False</li>
  <li>Regtest: False</li>
</ul>

**Comment by MentalNomad** [comment]
See also: [BTG Forum Post](https://forum.bitcoingold.org/t/fixing-server-is-lagging-in-electrumg/5555)

This problem might be fixed by deleting the blockchain headers and letting ElectrumG re-sync them from the servers. Here's how:

1. **Exit** ElectrumG. (On Windows, **Quitting** the wallet isn't enough; that just shrinks the app. Make sure to right-click and **Exit** from the task bar.)
1. **Navigate** to your `ElectrumG` data folder.
   On Windows, it's normally in `C:\Users\<usernme>\AppData\Roaming\ElectrumG` (see *note* below)
1. **Delete** the `blockchain_headers` file and the `forks` folder.
1. Start ElectrumG again.

***Do not** delete the* `wallets` *folder! That's where the critical information is for accessing your wallets and coins. If in any doubt, make a backup copy of your* `wallets` *folder.*

After restarting, ElectrumG should repeat the Bootstrap process and then re-sync the block headers from an ElectrumX server. This may take a couple of hours; on my run-of-the-mill desktop & internet connection, it took under two hours for over 600,000 block headers to sync.

---
*note*: If this is not where your ElectrumG folder is, then from the ElectrumG menu, do a `File` - `Open` and see where your `wallets` folder is. The default is inside the `ElectrumG` data folder, so this will show you where that is. But again, **do not delete** the `wallets` folder!
