### ISSUE TITLE
Server is lagging

### ISSUE THREAD

**Issue by warroc0** [BTCGPU/electrum#56]
<h2>Traceback</h2>
<pre>
Traceback (most recent call last):
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\util.py", line 770, in run_with_except_hook
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\network.py", line 1035, in run
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\network.py", line 969, in wait_on_sockets
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\network.py", line 627, in process_responses
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\network.py", line 573, in process_response
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\network.py", line 879, in on_get_header
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\blockchain.py", line 381, in write
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\blockchain.py", line 61, in write_file
  File "site-packages\electrumg-3.2.1-py3.5.egg\electrum\blockchain.py", line 377, in write_data
TypeError: a bytes-like object is required, not 'str'

</pre>

<h2>Additional information</h2>
<ul>
  <li>ElectrumG version: 3.2.1</li>
  <li>Operating system: Windows-10-10.0.19041-SP0</li>
  <li>Wallet type: standard</li>
  <li>Locale: nl_NL</li>
  <li>Testnet: False</li>
  <li>Regtest: False</li>
</ul>

at this moment the EU server is lagging 38 Blocks.

**Comment by MentalNomad** [comment]
See:

https://forum.bitcoingold.org/t/fixing-server-is-lagging-in-electrumg/5555

**Comment by MentalNomad** [comment]
See also: [BTG Forum Post](https://forum.bitcoingold.org/t/fixing-server-is-lagging-in-electrumg/5555)

This problem can be fixed by deleting the blockchain headers and letting ElectrumG re-sync them from the servers. Here's how:

1. **Exit** ElectrumG. (On Windows, **Quitting** the wallet isn't enough; that just shrinks the app. Make sure to right-click and **Exit** from the task bar.)
1. **Navigate** to your `ElectrumG` data folder.
   On Windows, it's normally in `C:\Users\<usernme>\AppData\Roaming\ElectrumG` (see *note* below)
1. **Delete** the `blockchain_headers` file and the `forks` folder.
1. Start ElectrumG again.

***Do not** delete the* `wallets` *folder! That's where the critical information is for accessing your wallets and coins. If in any doubt, make a backup copy of your* `wallets` *folder.*

After restarting, ElectrumG should repeat the Bootstrap process and then re-sync the block headers from an ElectrumX server. This may take a couple of hours; on my run-of-the-mill desktop & internet connection, it took under two hours for over 600,000 block headers to sync.

---
*note*: If this is not where your ElectrumG folder is, then from the ElectrumG menu, do a `File` - `Open` and see where your `wallets` folder is. The default is inside the `ElectrumG` data folder, so this will show you where that is. But again, **do not delete** the `wallets` folder!
